### ISSUE TITLE
Convert to ESP-IDF CMake toolchain and remove Arduino dependency

### ISSUE THREAD

**Issue by MauAbata** [MausTec/edge-o-matic-3000#3]
This is a "we should" as opposed to "we need to", but right now I'm building with Arduino which isn't very portable. I think the best practice in this regard is to use ESP-IDF toolchain.

I'd like a developer who is familiar with best practices specifically in regards to embedded / ESP-IDF development, and in application not just in theory, to weigh in here.

**Comment by MauAbata** [comment]
Working on this BTW as it became a "we need to". We're moving to PlatformIO which isn't purely IDF but gave me access to the IDF toolchain.

**Comment by B4ben-69** [comment]
i installed VScode with PlatformIO and it works like a charm.  No more Arduino IDE
