### ISSUE TITLE
Motor Start Speed seems broken

### ISSUE THREAD

**Issue by MauAbata** [MausTec/edge-o-matic-3000#30]
Customer is reporting that the motor start speed setting does not seem to change automatic functionality; motor still starts at 0.

This setting should also apply to manual mode, should it?

**Comment by B4ben-69** [comment]
In my opinion, the motor start speed should only be active in the automatic / auto+orgasm modes only, how else how can you determine the minimum speed to start if you don't test it in manual.

**Comment by B4ben-69** [comment]
I found the error with the minimum start speed. The minimum start speed menu has a index range of 150 compared to the max speed of 255. It`s only a perception error. i'll push a fix

**Comment by everevian** [comment]
Looks like this can be closed?

**Comment by B4ben-69** [comment]
Yes it's fixed in my pull

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
