### ISSUE TITLE
Error message at startup, any idea?

### ISSUE THREAD

**Issue by huajijam** [MausTec/edge-o-matic-3000#34]
[E][hal-eeprom.cpp:48] eeprom_init(): Hex right before load:
[E][hal-eeprom.cpp:62] eeprom_init(): Hex right after load:

**Comment by MauAbata** [comment]
Hey, those are actually debug messages, I just haven't removed them from the code.

I was abusing error-level logging to get through the log level filter. You can safely ignore this.
