### ISSUE TITLE
Software license

### ISSUE THREAD

**Issue by Galen-dp** [MausTec/edge-o-matic-3000#4]
I was wondering what software license is the source code using? And could it be made explicit with a LICENSE file?

**Comment by MauAbata** [comment]
Addressed this concern over here: https://github.com/MausTec/edge-o-matic-3000/pull/18#issuecomment-877858253

Discussion welcome, I guess in that thread then.

**Comment by MauAbata** [comment]
Alright how does GPLv3 sound? https://github.com/MausTec/edge-o-matic-3000/pull/20
