### ISSUE TITLE
Motor off delay and minimum speed setting

### ISSUE THREAD

**Issue by MauAbata** [MausTec/edge-o-matic-3000#6]
> It would be nice if there was a min motor speed and a delay till motor ramp start settings. So that you could have more control over the spacing. It’s also be fun to have patterns for the delays. So that you could push someone closer and closer and then a long cool down.

**Comment by MauAbata** [comment]
https://github.com/MausTec/nogasm-wifi/blob/master/src/OrgasmControl.cpp#L53-L54

This is where the speed ramps up, so to implement motor_min_speed here you'd do something like

```
if (motor_speed < 0) {
  motor_speed = Config.motor_min_speed;
} else {
  motor_speed += motor_increment;
}
```

Though it'd be a bit more complicated--right now we need to check if the current speed is < 0, and the new speed >= 0. So that should actually be:

```cpp
auto new_speed = motor_speed + motor_increment;
if (motor_speed < 0 && new_speed >= 0) {
  // Zero crossing / turn on detected
  motor_speed = Config.motor_min_speed;
} else {
  motor_speed = new_speed;
}
```

**Comment by krishpants** [comment]
Potentially fixed in my PR
